### PR TITLE
[RTM] Offer the Contao 4 backend filter panel buttons

### LINKED ISSUE #202: Reset all filters button at backend
Add some button next to the "apply" circle to clear all current filters.
See contao/core#6239

### PR DESCRIPTION
**Pull request by cliffparnitzky**
Offer the Contao 4 backend filter panel buttons and inserts the reset filter button (may close #202).

The result will be: 
image

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [x] Created tests, if possible
- [ ] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by cliffparnitzky** [comment]
My latest test showed, that the reset is not working proper all time. Clicking it once, all filters and the search will be cleared ... but after a browser refresh, they are pre-selected. Hopefully @baumannsven can see the reason.

**Review by zonky2 — APPROVED** [review]
tested with mm210 - works fine

**Comment by cliffparnitzky** [comment]
@zonky2 : Attention, this is still a problem

> My latest test showed, that the reset is not working proper all time. Clicking it once, all filters and the search will be cleared ... but after a browser refresh, they are pre-selected. Hopefully @baumannsven can see the reason.

Another case is: reset the filters, add a new item --> filters are pre-selected

**Comment by zonky2** [comment]
upps - I dont see this https://github.com/contao-community-alliance/dc-general/pull/555#issuecomment-724310340 :(
sounds like a session problem - still the problem after reset your user session in profile?

**Comment by cliffparnitzky** [comment]
The persisted search/filter values still had to be deleted. Finalized this in 014f364375e69e93a31e130d7c0cc33ee7f6029c

**Review by baumannsven — APPROVED** [review]

**Comment by baumannsven** [comment]
Merged in 5cbbfa14ab823385e6f98b414fff03bb7d2a0efc

**Pull request closed without merging**
