### PR TITLE
Remove legacy dependencies.

### PR DESCRIPTION
**Pull request by richardhj**
## Description

I removed the dependency on the package [`contao-community-alliance/dependency-container`](https://github.com/contao-community-alliance/dependency-container)
because it requires `pimple/pimple` in version 1.0. This conflicts with  [Deployer](https://github.com/deployphp/deployer), which requires Pimple in version 3.

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by richardhj** [comment]
Where do you see a BC problem here (I know, there is a small bc break in MetaModels/core#1314)

**Comment by discordier** [comment]
If anyone ever swapped any service in pimple, that service will not be swapped in the Symfony DC.
Therefore now a different service would be in use. Admitted, this is an extremely corner case but was still possible.

**Comment by baumannsven** [comment]
Merged in 19cd00a9f7761e47d6705db90595fdd6fbd88ec7

**Comment by discordier** [comment]
Why isn't this closed after merge?
Should we document the bc breaks?

**Pull request closed without merging**
