### PR TITLE
added more flexibility to the idgeneration

### PR DESCRIPTION
**Pull request by cboelter**
As discussed yesterday a have reworked the idGenerator a litte bit. Now it is possible to pass the idGenerator instance in the DCA-Config. So it is possible to change it easy to another generator.
I have changed the IdGeneratorInterface to fit to this new way.

@discordier please have a look on it and give feedback :)

### CODE REVIEW

**Comment by discordier** [comment]
The generic interface should not need a setDatabase as it is potentially originating from somewhere else.

Now you enforce everyone to accept a database connection whereas when implementing an php only uuid generator that one will never need it.

I did like the constructor injection there as the relevant stuff to generate ids should get injected and masked away from the concrete driver.

Think of them as stuff in entirely different domains, they do not have to know about connections etc. of the other one as long as it works.

**Comment by cboelter** [comment]
@discordier i removed the setDabase from the Interface and changed the Database passing to the constructor of the DatabaseUuidIdGenerator class. I think you are right, so we have separated it from the driver.

What do you think?

**Comment by cboelter** [comment]
@discordier is it now ready to merge? I need this feature :)

**Comment by cboelter** [comment]
Waiting for feedback :(

**Comment by discordier** [comment]
sorry, I thought you had read the scrutinizer report.
https://scrutinizer-ci.com/g/contao-community-alliance/dc-general/inspections/64c6e9af-28b2-445a-9b4a-b92b87a60ca5/issues/files/src/ContaoCommunityAlliance/DcGeneral/Data/DefaultDataProvider.php?status=new&orderField=path&order=asc
There are still 3 issues you introduced.

**Comment by cboelter** [comment]
Oh I see, will fix it as fast as possible!

**Comment by cboelter** [comment]
@discordier I think scrutinizer is now happy :) ...

**Pull request merged**
