### PR TITLE
Prepare clipboard to deal with model ids. 

### PR DESCRIPTION
**Pull request by dmolineus**
This pull request rewrites some parts of the clipboard handling so that only valid `ModelIds` are used.

As discussed the `ItemInterface` got extended. Additional I had to add an `getDataProviderName` method as well for items without an model id.

It's not ready tested yet, just to inform that the work is basically done. Have a further look this weekend.

### CODE REVIEW

**Comment by discordier** [comment]
I hvae some additions, see https://github.com/dmolineus/dc-general/pull/2.

A lot of unit tests are missing though as I only started them.

**Comment by MacKP** [comment]
Als Erinnerung:
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Data/ModelId.php on line 116

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(163): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized(NULL)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(185): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->buildBaseConfig(NULL)
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Event/Subscriber.php(356): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->getBaseConfig()
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Event\Subscriber->initializePanels(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#7 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#9 contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_re...')
#10 contao/main.php(288): Main->run()
#11 {main}
```

**Comment by discordier** [comment]
@dmolineus As I have no time currently to work on DCG and MM, could you finish this one and the other depending PRs?

**Comment by dmolineus** [comment]
@discordier Yes, I will have a look on it. I'm currently have a MM project where I plan to finish it. Basically it's finished. Just the unit test aren't completed.

**Comment by discordier** [comment]
@dmolineus Ping? :)

**Comment by dmolineus** [comment]
I did not forget it. It's on my todo list. Have a look on it next week (KW 46).

**Comment by dmolineus** [comment]
Found some time this week. I added the missing filter tests, fixed some filter logic. From my point it's RTM now.

**Comment by discordier** [comment]
The file header of the mocked test is not correct. Aside from that it looks great. @stefanheimes any objections?

**Comment by dmolineus** [comment]
Updated the test file headers.

**Comment by dmolineus** [comment]
Great! :+1:  

This is the follow up PR for MetaModels which make usage of the changed API and can be merged now: https://github.com/MetaModels/core/pull/856

**Pull request merged**
