### PR TITLE
Feature/filetree thumbnail size

### PR DESCRIPTION
**Pull request by zonky2**
add getter and setter for thumbnail witdh, height and placeholder

### CODE REVIEW

**Comment by xantippe** [comment]
Tests:
default:
shot168

big image
shot169

small image
shot170

**Comment by discordier** [comment]
I have resolved the conflicts and merged this in 25d9992f537a515b799f7ead8933764366b9acbf

**Comment by zonky2** [comment]
Tahnks

**Comment by zonky2** [comment]
looks good!

shot258

**Pull request closed without merging**
