### PR TITLE
Feature/deep delete

### PR DESCRIPTION
**Pull request by baumannsven**
DCG has now handling delete all child elements

### CODE REVIEW

**Comment by stefanheimes** [comment]
Looks good, i have to test it.

At the moment I see only some small errors like the code styling and the missing name, mail in the top of the phpdoc.

See: https://travis-ci.org/contao-community-alliance/dc-general/jobs/118483303#L420

**Comment by baumannsven** [comment]
@stefanheimes i have add missing author and format code. is this good for you?

**Comment by stefanheimes** [comment]
Jip looks nice and sweet. Not perfect but i have to add some missings things from me too.

**Comment by baumannsven** [comment]
Can you say what

**Comment by stefanheimes** [comment]
First you can use this https://scrutinizer-ci.com/g/contao-community-alliance/dc-general/inspections/3a342896-2154-4e1e-a485-b2983b551a89/issues/files/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/DeleteHandler.php?status=new&selectedLabels%5B0%5D=6&selectedLabels%5B1%5D=3&selectedLabels%5B2%5D=8&orderField=path&order=asc&fileId=src%2FContaoCommunityAlliance%2FDcGeneral%2FContao%2FView%2FContao2BackendView%2FActionHandler%2FDeleteHandler.php&honorSelectedPaths=0

and

https://travis-ci.org/contao-community-alliance/dc-general/jobs/125538952#L663

Here you can see the most errors.

**Comment by baumannsven** [comment]
I have fixed phpcs and phpmd issues.

I have trouble with missing @return tag in function comment.
https://travis-ci.org/contao-community-alliance/dc-general/jobs/127490187#L680
Can you say what todo for missing return tag. This function don´t return anything.

@stefanheimes

**Comment by stefanheimes** [comment]
If the function don't retun any, do it like Java use the "void" keyword. 
```
/*
 * @return void
 */
```

**Comment by baumannsven** [comment]
Thanks. I'm add this later. Then you can merge this pull request.

**Comment by discordier** [comment]
Thanks for squasing, now it is way more readable. @stefanheimes seems good to merge.

**Comment by stefanheimes** [comment]
Merged on current hotfix 35. Thanks for PR.

**Pull request closed without merging**
