### PR TITLE
[RTM] Do not add saveNclose if "nb" parameter given

### PR DESCRIPTION
**Pull request by richardhj**
## Description

Same procedure as in DC_Table.
https://github.com/contao/contao/blob/812ac06cd1c6f6c775e0dbca2547d89b3be36a2d/core-bundle/src/Resources/contao/drivers/DC_Table.php#L2000

Useful if you have a popup link on an edit mask. In this case, you don't need a back link.

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [x] Created tests, if possible
- [x] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [x] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by discordier** [comment]
Shouldn't `nc` be handled as well then? See the block just below your linked code.

**Comment by richardhj** [comment]
In the current implementation of the DCG, "nc" is the default when in a popup (`popup=1`).

**Comment by discordier** [comment]
You are right, missed that. This now raises the question if it should only if there is `nc` present for consistency...?

**Comment by richardhj** [comment]
> You are right, missed that. This now raises the question if it should only if there is nc present for consistency...?

I don't think that this will be a serious BC break and I will update the code according to this.

**Comment by baumannsven** [comment]
I move this on 2.1.5. I must show what parameter nc do in dc table

**Comment by discordier** [comment]
@baumannsven You closed this PR instead of moving?

**Comment by baumannsven** [comment]
Ups i used the wrong button.

@discordier Why i can not reopen this?

**Comment by discordier** [comment]
I guess because the source branch is in the same repo... maybe github changed something so that PR originating from the same Repo can't be reopened... We need a replacement PR (targeted at master).

**Comment by baumannsven** [comment]
Thats right. Here can you see the `DC_TABLE` use the parameter for `no save and back` `nb`.

https://github.com/contao/core-bundle/blob/16b52a055d4c12d09b47f21798efe8331f065e67/src/Resources/contao/drivers/DC_Table.php#L2000

I see a second parameter for handle the `no save create` `nc`. This parameter check should be support too.

**Comment by richardhj** [comment]
Merged.

**Comment by zonky2** [comment]
ahh - "nb" means "no back button"

https://github.com/contao/contao/blob/812ac06cd1c6f6c775e0dbca2547d89b3be36a2d/core-bundle/src/Resources/contao/classes/Backend.php#L240-L241

**Comment by baumannsven** [comment]
merged in 6edcb7536eab0812aa3de674d165021ef77cfc1c

**Pull request closed without merging**
