### PR TITLE
Update vanillaGeneral.js

### LINKED ISSUE #161: Popup-Tags werden nicht übernommen
Fehler ist aufgetreten bei MetaModels, wenn hier versucht wird im Fenster vom GeneralTreePicker eine Mehrfach Auswahl zu übernehmen, gibt es einen JS Fehler.

Siehe: https://github.com/MetaModels/core/issues/883

### PR DESCRIPTION
**Pull request by MoniqueHahnefeld**
fix #161

### CODE REVIEW

**Comment by discordier** [comment]
@stefanheimes could you check this please?

**Comment by stefanheimes** [comment]
Sorry for it, i have to apologize. We already have a bugfix for it. There is a hotfix branch with the changes for the js 

But not yet merged into the master and dev. I will do it this evening and add a new version. 

Thanks for the PR.

**Comment by stefanheimes** [comment]
Merge done new Version 2.0.0-beta29. Can you please check it.

**Comment by MoniqueHahnefeld** [comment]
@stefanheimes no prob :D ...

**Pull request closed without merging**
