### PR TITLE
Hotfix #215 filter be value with special chars

### PR DESCRIPTION
**Pull request by zonky2**
allow to filter values with special chars like double-quotes, greater, lesser

### CODE REVIEW

**Comment by zonky2** [comment]
@discordier you see problems or side effects with this implemention... or it´s o.k.?

**Comment by discordier** [comment]
Should be good IMO.

**Comment by zonky2** [comment]
it´s possible to merge it?

**Comment by discordier** [comment]
Merged in eba380b80487cb3813a38145ea1e9030806e7855

**Pull request closed without merging**
