### PR TITLE
Fix data type mismatch

### PR DESCRIPTION
**Pull request by binron**
setFields expects an array, getToggleProperty returns a string

### CODE REVIEW

**Comment by binron** [comment]
@discordier can you merge this fix?

**Comment by zonky2** [comment]
@binron it´s not possible... 

please add your signet as author at the header for the code and add you at https://github.com/contao-community-alliance/dc-general/blob/master/.check-author.yml

btw: the same at your PR in MetaModels

**Comment by zonky2** [comment]
may be other guy make your job... https://github.com/MetaModels/core/pull/1039

**Comment by binron** [comment]
Seems to be not possible

**Comment by zonky2** [comment]
> Seems to be not possible

why?

**Comment by binron** [comment]
You are free to merge but I can not spend more time on it
as it took me a already a long time to fix these two bugs (#1035).
It's a very small fix and easy to understand so just merge it or not.

**Comment by micbis** [comment]
@zonky2  Is there any chance that you merge this one into the hotfix branch soon? This would help a lot of us... and we no longer have to maintain our own repositories.

**Comment by zonky2** [comment]
sorry, I work only in the "digital coal cellar" ;-)

tagging and merging is the job for the man on the "ship's bridge" - and this is @discordier 

... I hope, he can do this soon

**Comment by discordier** [comment]
Merged in b3b5203ade2645c30c955c490a306f1385f4bb41

**Comment by micbis** [comment]
Thanks guys!

**Pull request closed without merging**
