### PR TITLE
Introduce a service for the translator.

### PR DESCRIPTION
**Pull request by dmolineus**
This pull request provides the translator as service. This can be useful when the environment isn't build yet, e.g. in https://github.com/MetaModels/core/blob/tng/src/MetaModels/DcGeneral/Dca/Builder/Builder.php

### CODE REVIEW

**Comment by dmolineus** [comment]
That's what I actually wanted. The translator is no contao-module, yet. Defining services isn't possible yet. That's why I added it here.

The translator has already an indirect dependency to contao by the `event-dispatcher`. So changing the module type/requirements shouldn't break any third party system. Contao is already required.

**Comment by dmolineus** [comment]
I adjusted the composer requirement now. However this could make the dc general uninstallable if any third party extension requires v1. I checked MetaModels, there is no defined dependency for the translator.

**Comment by discordier** [comment]
Which is perfectly fine, as that's the whole point behind semantic versioning. :)

We now can use the translator in MetaModels as well and therefore add it there also, but this is a low priority task so far.

**Comment by dmolineus** [comment]
Yeah I know, but it's a hidden change as the dc general is still in beta and won't get bumped to a next major version. ;)

**Comment by discordier** [comment]
As you said, we are still in beta and not RC yet so we could enhance the interface.

What do the others think? @tim-bec, @stefanheimes?

**Comment by tim-bec** [comment]
Enhance it. But lets talk about a feature freeze and RC tomorrow?

**Comment by discordier** [comment]
Yep. We also should declare everything not currently defined as interface to not be part of the API and therefore may break within minors.
So only the interfaces will be supported throughout the major version and everything else is subject to break.

**Pull request merged**
