### PR TITLE
[RTM] Improvements when implementing own parented list view handler

### PR DESCRIPTION
**Pull request by richardhj**
## Description

These improvements are necessary creating my own ListViewHandler which `extends ParentedListViewShowAllHandler`.

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [x] Created tests, if possible
- [ ] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by discordier** [comment]
Looks good to me.

**Comment by zonky2** [comment]
@richardhj pls check edit/overrideAll

**Comment by zonky2** [comment]
@baumannsven testet at testcase - no error found

**Comment by baumannsven** [comment]
Merged in 55b49aee55eeb1a6fca803563064e348b3ff5114

**Pull request merged**
