### PR TITLE
Fixes problem with wrong null check

### PR DESCRIPTION
**Pull request by cliffparnitzky**

### CODE REVIEW

**Comment by discordier** [comment]
This implementation will introduce yet another PHP notice, we should not do this.
could you change this to:
```diff
- && isset($properties->getProperty($property)->getExtra()['alwaysSave'])
+ && ($extra = $properties->getProperty($property)->getExtra()) && isset($extra['alwaysSave'])
```

Imo this should work too and not cause any notice, warning or anything else.

**Comment by cliffparnitzky** [comment]
Yep, looks good. I have changed the code.

**Comment by dillinja** [comment]
Clean Contao 3.5.15
PHP: 5.6.23
MM-Core: 2.0.0-alpha13
dc-general: dev-hotfix/beta-38

Clean Installation of Contao **->** Composer **->** MM bundle_all **->** isset() - Error **->** dev-hotfix/beta-38

Error occurs when clicking on 'New Metamodel'

```
[23-Aug-2016 12:15:25 Europe/Berlin] PHP Fatal error: Uncaught exception 'RuntimeException' with message 'I should not be here! :-\' thrown in J:\Projekte\___Xampp\htdocs\test\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php on line 395
#0 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->create(Object(ContaoCommunityAlliance\DcGeneral\Action))
#1 J:\Projekte\___Xampp\htdocs\test\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(142): call_user_func_array(Array, Array)
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 J:\Projekte\___Xampp\htdocs\test\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 J:\Projekte\___Xampp\htdocs\test\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 J:\Projekte\___Xampp\htdocs\test\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 J:\Projekte\___Xampp\htdocs\test\composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 J:\Projekte\___Xampp\htdocs\test\system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#8 J:\Projekte\___Xampp\htdocs\test\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#9 J:\Projekte\___Xampp\htdocs\test\contao\main.php(20): Contao\BackendMain->run()
#10 {main}
```

**Comment by zonky2** [comment]
the next update is in our pipeline... you can test the new PR https://github.com/contao-community-alliance/dc-general/pull/299

**Comment by dillinja** [comment]
thx - PR #299 works fine.

**Comment by zonky2** [comment]
you can use the current DCG beta38 631380a

**Comment by akroii** [comment]
But when i fix [https://github.com/contao-community-alliance/dc-general/pull/288/commits/8e46e8d51849bb779a0b91df26c24ed427733285#diff-eb7eae3d0cbe8d67765cfea7ff120f2aR381](url)
i get another error:
PHP Fatal error:  Call to a member function setResponse() on null in C:\xampp\htdocs\test\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php on line 145

I am using:
MM 2.0.0 Referenz: f335503c

**Comment by zonky2** [comment]
@akroii pls install hotfix/beta-38 per composer

**Comment by akroii** [comment]
You mean contao-community-alliance/dc-general	2.0.0-beta37 → dev-hotfix/beta-38?
getting this error:
```
Dependency "contao/core" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "contao/core" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "contao/core" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "contao/core" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "contao/core" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "contao/core" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - metamodels/attribute_select 2.0.0-alpha11 requires contao-community-alliance/dc-general ~2.0 -> satisfiable by contao-community-alliance/dc-general[2.0.x-dev].
    - metamodels/attribute_select 2.0.0-alpha11 requires contao-community-alliance/dc-general ~2.0 -> satisfiable by contao-community-alliance/dc-general[2.0.x-dev].
    - metamodels/attribute_select 2.0.0-alpha11 requires contao-community-alliance/dc-general ~2.0 -> satisfiable by contao-community-alliance/dc-general[2.0.x-dev].
    - Can only install one of: contao-community-alliance/dc-general[dev-hotfix/beta-38, 2.0.x-dev].
    - Installation request for contao-community-alliance/dc-general dev-hotfix/beta-38 -> satisfiable by contao-community-alliance/dc-general[dev-hotfix/beta-38].
    - Installation request for metamodels/attribute_select (locked at 2.0.0-alpha11) -> satisfiable by metamodels/attribute_select[2.0.0-alpha11].```

**Comment by zonky2** [comment]
pls read the maual http://metamodels.readthedocs.io/de/latest/manual/install.html#test-von-speziellen-paketen-via-composer

http://metamodels.readthedocs.io/en/latest/manual/install.html#testing-of-special-packages-via-composer

and add ```as 2.0.0```

**Comment by akroii** [comment]
thanks a lot

**Comment by zonky2** [comment]
=> this is the right page https://now.metamodel.me/en/supporters/donate ;-)

**Comment by zonky2** [comment]
Thanks for your donate!

**Comment by akroii** [comment]
Thank you for your community support;)

**Pull request merged**
