### PR TITLE
Minor SCA fixes.

### PR DESCRIPTION
**Pull request by richardhj**
## Description

Minor sca fixes.

## Checklist
- [ ] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by baumannsven** [comment]
@richardhj Please fix the travis issues and add more description.

**Comment by richardhj** [comment]
I don't know how to fix the ERROR | Empty CATCH statement detected.
This PR fixes some errors found by a static code analyzes.
Among others:
- Catch potential ReflectionException
- Fix return type definition
- Fix typo
- Fix redundant variable definition (inline variables)
- simplify return value

**Comment by baumannsven** [comment]
@richardhj I thinks you must @throws exception description in the method doc for isGetOptionsAllowed

**Comment by baumannsven** [comment]
@richardhj If the class not exists, then is this an error or? So we can throw a DcGeneralRuntimeException. What do you mean?

**Comment by baumannsven** [comment]
Merged in 750a29f41825e15ea0b64603c5bed5a1ea677338

**Pull request merged**
